// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: messages.proto

#include "messages.pb.h"
#include "messages.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace partition_oram {

static const char* server_method_names[] = {
  "/partition_oram.server/init_oram",
  "/partition_oram.server/read_block",
  "/partition_oram.server/write_block",
  "/partition_oram.server/key_exchange",
};

std::unique_ptr< server::Stub> server::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< server::Stub> stub(new server::Stub(channel, options));
  return stub;
}

server::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_init_oram_(server_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_read_block_(server_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_write_block_(server_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_key_exchange_(server_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status server::Stub::init_oram(::grpc::ClientContext* context, const ::partition_oram::InitOramRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::partition_oram::InitOramRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_init_oram_, context, request, response);
}

void server::Stub::async::init_oram(::grpc::ClientContext* context, const ::partition_oram::InitOramRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::partition_oram::InitOramRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_init_oram_, context, request, response, std::move(f));
}

void server::Stub::async::init_oram(::grpc::ClientContext* context, const ::partition_oram::InitOramRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_init_oram_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* server::Stub::PrepareAsyncinit_oramRaw(::grpc::ClientContext* context, const ::partition_oram::InitOramRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::partition_oram::InitOramRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_init_oram_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* server::Stub::Asyncinit_oramRaw(::grpc::ClientContext* context, const ::partition_oram::InitOramRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncinit_oramRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status server::Stub::read_block(::grpc::ClientContext* context, const ::partition_oram::ReadBlockRequest& request, ::partition_oram::ReadBlockResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::partition_oram::ReadBlockRequest, ::partition_oram::ReadBlockResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_read_block_, context, request, response);
}

void server::Stub::async::read_block(::grpc::ClientContext* context, const ::partition_oram::ReadBlockRequest* request, ::partition_oram::ReadBlockResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::partition_oram::ReadBlockRequest, ::partition_oram::ReadBlockResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_read_block_, context, request, response, std::move(f));
}

void server::Stub::async::read_block(::grpc::ClientContext* context, const ::partition_oram::ReadBlockRequest* request, ::partition_oram::ReadBlockResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_read_block_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::partition_oram::ReadBlockResponse>* server::Stub::PrepareAsyncread_blockRaw(::grpc::ClientContext* context, const ::partition_oram::ReadBlockRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::partition_oram::ReadBlockResponse, ::partition_oram::ReadBlockRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_read_block_, context, request);
}

::grpc::ClientAsyncResponseReader< ::partition_oram::ReadBlockResponse>* server::Stub::Asyncread_blockRaw(::grpc::ClientContext* context, const ::partition_oram::ReadBlockRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncread_blockRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status server::Stub::write_block(::grpc::ClientContext* context, const ::partition_oram::WriteBlockRequest& request, ::partition_oram::WriteBlockResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::partition_oram::WriteBlockRequest, ::partition_oram::WriteBlockResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_write_block_, context, request, response);
}

void server::Stub::async::write_block(::grpc::ClientContext* context, const ::partition_oram::WriteBlockRequest* request, ::partition_oram::WriteBlockResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::partition_oram::WriteBlockRequest, ::partition_oram::WriteBlockResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_write_block_, context, request, response, std::move(f));
}

void server::Stub::async::write_block(::grpc::ClientContext* context, const ::partition_oram::WriteBlockRequest* request, ::partition_oram::WriteBlockResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_write_block_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::partition_oram::WriteBlockResponse>* server::Stub::PrepareAsyncwrite_blockRaw(::grpc::ClientContext* context, const ::partition_oram::WriteBlockRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::partition_oram::WriteBlockResponse, ::partition_oram::WriteBlockRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_write_block_, context, request);
}

::grpc::ClientAsyncResponseReader< ::partition_oram::WriteBlockResponse>* server::Stub::Asyncwrite_blockRaw(::grpc::ClientContext* context, const ::partition_oram::WriteBlockRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncwrite_blockRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status server::Stub::key_exchange(::grpc::ClientContext* context, const ::partition_oram::KeyExchangeRequest& request, ::partition_oram::KeyExchangeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::partition_oram::KeyExchangeRequest, ::partition_oram::KeyExchangeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_key_exchange_, context, request, response);
}

void server::Stub::async::key_exchange(::grpc::ClientContext* context, const ::partition_oram::KeyExchangeRequest* request, ::partition_oram::KeyExchangeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::partition_oram::KeyExchangeRequest, ::partition_oram::KeyExchangeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_key_exchange_, context, request, response, std::move(f));
}

void server::Stub::async::key_exchange(::grpc::ClientContext* context, const ::partition_oram::KeyExchangeRequest* request, ::partition_oram::KeyExchangeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_key_exchange_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::partition_oram::KeyExchangeResponse>* server::Stub::PrepareAsynckey_exchangeRaw(::grpc::ClientContext* context, const ::partition_oram::KeyExchangeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::partition_oram::KeyExchangeResponse, ::partition_oram::KeyExchangeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_key_exchange_, context, request);
}

::grpc::ClientAsyncResponseReader< ::partition_oram::KeyExchangeResponse>* server::Stub::Asynckey_exchangeRaw(::grpc::ClientContext* context, const ::partition_oram::KeyExchangeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynckey_exchangeRaw(context, request, cq);
  result->StartCall();
  return result;
}

server::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      server_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< server::Service, ::partition_oram::InitOramRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](server::Service* service,
             ::grpc::ServerContext* ctx,
             const ::partition_oram::InitOramRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->init_oram(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      server_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< server::Service, ::partition_oram::ReadBlockRequest, ::partition_oram::ReadBlockResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](server::Service* service,
             ::grpc::ServerContext* ctx,
             const ::partition_oram::ReadBlockRequest* req,
             ::partition_oram::ReadBlockResponse* resp) {
               return service->read_block(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      server_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< server::Service, ::partition_oram::WriteBlockRequest, ::partition_oram::WriteBlockResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](server::Service* service,
             ::grpc::ServerContext* ctx,
             const ::partition_oram::WriteBlockRequest* req,
             ::partition_oram::WriteBlockResponse* resp) {
               return service->write_block(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      server_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< server::Service, ::partition_oram::KeyExchangeRequest, ::partition_oram::KeyExchangeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](server::Service* service,
             ::grpc::ServerContext* ctx,
             const ::partition_oram::KeyExchangeRequest* req,
             ::partition_oram::KeyExchangeResponse* resp) {
               return service->key_exchange(ctx, req, resp);
             }, this)));
}

server::Service::~Service() {
}

::grpc::Status server::Service::init_oram(::grpc::ServerContext* context, const ::partition_oram::InitOramRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status server::Service::read_block(::grpc::ServerContext* context, const ::partition_oram::ReadBlockRequest* request, ::partition_oram::ReadBlockResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status server::Service::write_block(::grpc::ServerContext* context, const ::partition_oram::WriteBlockRequest* request, ::partition_oram::WriteBlockResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status server::Service::key_exchange(::grpc::ServerContext* context, const ::partition_oram::KeyExchangeRequest* request, ::partition_oram::KeyExchangeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace partition_oram

